[agent]
  interval = "3s"
  flush_interval = "3s"

[[inputs.docker]]
  endpoint = "tcp://socket-proxy:2375"
  container_name_include = ["*fastapi*", "*nodejs*", "*springboot*"]
  container_name_exclude = []
  timeout = "5s"
  perdevice = false
  total = false

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "k6"
